from browser_agent_v1.providers.base import ProviderPlaybook

PLAYBOOK = ProviderPlaybook(
    provider="greenhouse",
    apply_entry_selectors=("#application_button", "a#application_button", "a:has-text('Apply for this job')"),
    resume_upload_selectors=("input[name='resume']", "input[name='cover_letter']", "input[type='file']"),
    upload_confirmation_selectors=("text=/resume|cover letter/i", ".resume", "[data-source='resume']"),
    screening_field_selectors=("label", "fieldset", ".application-question"),
    submit_selectors=("button:has-text('Submit Application')", "button#submit_app", "input[type='submit']", "text=/review application/i"),
    login_selectors=("input[type='email']", "input[name='email']", "button:has-text('Sign In')"),
    signup_selectors=("a:has-text('Create account')", "button:has-text('Create account')"),
    login_email_selectors=("input[type='email']", "input[name='email']", "input[autocomplete='username']"),
    login_password_selectors=("input[type='password']", "input[name='password']", "input[autocomplete='current-password']"),
    login_submit_selectors=("button:has-text('Sign In')", "button[type='submit']"),
    login_success_selectors=("text=/application submitted|application form|my account/i",),
    invalid_credentials_selectors=(".field-error", ".error", "text=/incorrect password|invalid login/i"),
    signup_name_selectors=("input[name='first_name']", "input[name='last_name']", "input[autocomplete='given-name']", "input[autocomplete='family-name']"),
    signup_email_selectors=("input[type='email']", "input[name='email']", "input[autocomplete='email']"),
    signup_password_selectors=("input[type='password']", "input[name='password']", "input[autocomplete='new-password']"),
    signup_submit_selectors=("button:has-text('Create account')", "button:has-text('Continue')", "button[type='submit']"),
    signup_success_selectors=("text=/application form|start your application|continue/i",),
    duplicate_account_selectors=("text=/already have an account|email already in use|account already exists/i",),
    account_recovery_selectors=("text=/forgot password|reset password/i",),
    review_boundary_selectors=("text=/review application|application review/i",),
    validation_selectors=(".field-error", ".error", "[aria-invalid='true']"),
    pause_triggers=("captcha", "manual review", "consent widget", "duplicate account"),
    notes=("Greenhouse is usually account-light; account selectors are opportunistic and low-risk.",),
)
